### ISSUE TITLE
Pre-request Script "Cannot read property 'length' of undefined" Error

### ISSUE THREAD

**Issue by DAZCUK46** [sajeetharan/cosmosdb-api-test#1]
Hi
Unable to get any of the requests to work receiving this error message "There was an error in evaluating the Pre-request Script:  TypeError: Cannot read property 'length' of undefined"  

![pre-request script error](https://user-images.githubusercontent.com/29930723/64773237-e8687700-d549-11e9-8fcf-e0274255b09b.JPG)

![env settings](https://user-images.githubusercontent.com/29930723/64772944-65472100-d549-11e9-9b09-38e0971c5423.JPG)

**Comment by KalyanChanumolu-MSFT** [comment]
@DAZCUK46 

Open the **CosmosDB_postman_collection.json** file, 
replace "DocumentDBMasterKey" with "CosmosDBMasterKey"
replace "DocumentDBAPIVersion" with "CosmosDBAPIVersion"

Import the file again and replace existing collection. You should be good to go.
I will submit a PR to fix the issue.

**Comment by DAZCUK46** [comment]
> @DAZCUK46
> 
> Open the **CosmosDB_postman_collection.json** file,
> replace "DocumentDBMasterKey" with "CosmosDBMasterKey"
> replace "DocumentDBAPIVersion" with "CosmosDBAPIVersion"
> 
> Import the file again and replace existing collection. You should be good to go.
> I will submit a PR to fix the issue.

Fantastic all works now, thanks for resolving

**Comment by KalyanChanumolu-MSFT** [comment]
@DAZCUK46 PR is merged. 
Please close this issue now.
